# Generated by Django 5.1.4 on 2025-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0004_movie_created_by_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='learndjango.tags'),
        ),
    ]
