# Generated by Django 5.1.4 on 2025-01-06 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0006_alter_movie_tag_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profilePic',
        ),
    ]
