# Generated by Django 5.1.4 on 2025-01-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
