# Generated by Django 5.1.4 on 2025-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
