# Generated by Django 5.1.4 on 2025-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0013_alter_profile_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
